CREATE TABLE BACKUP (
    BACKUP_ID INT UNSIGNED PRIMARY KEY,
    BackupType INT UNSIGNED,
    Date DATE,
    Location VARCHAR(20),
    OBJECT_Object_ID INT UNSIGNED NOT NULL
);
CREATE TABLE REF_PRIVILEGE (
    Privilege_ID INT UNSIGNED PRIMARY KEY,
    SUBJECT_Subject_ID INT UNSIGNED,
    OBJECT_Object_ID INT UNSIGNED,
    PRIVILEGE_TYPE_Privilege_Type_ID INT UNSIGNED NOT NULL
);
CREATE TABLE PRIVILEGE_TYPE (
    Privilege_Type_ID INT UNSIGNED PRIMARY KEY,
    Name INT
);
CREATE TABLE SUBJECT (
    Subject_ID INT UNSIGNED PRIMARY KEY,
    Name VARCHAR(20),
    USER_User_ID INT UNSIGNED NOT NULL
);
CREATE TABLE CLASSIFICATION (
    Classification_ID INT UNSIGNED PRIMARY KEY,
    Name VARCHAR(20)
);
CREATE TABLE OBJECT (
    Object_ID INT UNSIGNED PRIMARY KEY,
    OBJECT_TYPE_Object_Type_ID INT UNSIGNED NOT NULL,
    CLASSIFICATION_Classification_ID INT UNSIGNED NOT NULL
);
CREATE TABLE OBJECT_TYPE (
    Object_Type_ID INT UNSIGNED PRIMARY KEY,
    Name VARCHAR(1)
);
CREATE TABLE ITSYSTEM (
    System_ID INTEGER UNSIGNED PRIMARY KEY,
    Name VARCHAR(20),
    Hardware TEXT,
    Type CHAR(1),
    ITSYSTEM_System_ID INTEGER UNSIGNED NOT NULL,
    EMPLOYEE_Employee_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE USER (
    User_ID INTEGER UNSIGNED PRIMARY KEY,
    Username VARCHAR(20),
    Account_Status VARCHAR(20),
    Password_short VARCHAR(20),
    Date_Added DATE,
    Date_Deleted DATE,
    EMPLOYEE_Employee_ID INTEGER UNSIGNED NOT NULL,
    ITSYSTEM_System_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE EMPLOYEE (
    Employee_ID INTEGER UNSIGNED PRIMARY KEY,
    Last_Name NVARCHAR(20),
    First_Name NVARCHAR(20),
    Email NVARCHAR(20),
    Phone NVARCHAR(15),
    Position VARCHAR(20)
);
CREATE TABLE ROLE (
    Role_ID INTEGER UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20),
    Description TEXT,
    ITSYSTEM_System_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE PRIVILEGE (
    Privilege_ID INTEGER UNSIGNED PRIMARY KEY,
    PRIVILEGE_TYPE_Privilege_Type_ID INTEGER UNSIGNED NOT NULL,
    OPERATION_Operation_ID INTEGER UNSIGNED NOT NULL,
    ROLE_Role_ID INTEGER UNSIGNED NOT NULL,
    OBJECT_Object_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE OPERATION (
    Operation_ID INTEGER UNSIGNED PRIMARY KEY,
    Name VARCHAR(20),
    ITSYSTEM_System_ID INTEGER UNSIGNED,
    OPERATION_TYPE_Operation_Type_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE OPERATION_TYPE (
    Operation_Type_ID INTEGER UNSIGNED PRIMARY KEY,
    Name VARCHAR(20)
);
CREATE TABLE EVENT (
    Event_ID INT UNSIGNED PRIMARY KEY,
    Session_Id VARCHAR(20),
    Attempt_result VARCHAR(20),
    Date DATE,
    Message NVARCHAR(1),
    New_value NVARCHAR(20),
    Old_value NVARCHAR(20),
    EVENT_TYPE_Event_Type_ID INT UNSIGNED NOT NULL,
    OBJECT_Object_ID INT UNSIGNED NOT NULL,
    ITSYSTEM_System_ID INT UNSIGNED NOT NULL,
    USER_User_ID INT UNSIGNED NOT NULL,
    ROLE_Role_ID INT UNSIGNED NOT NULL,
    OBJECT_Object_ID2 INT UNSIGNED NOT NULL,
    OPERATION_Operation_ID INT UNSIGNED NOT NULL
);
CREATE TABLE EVENT_TYPE (
    Event_Type_ID INTEGER UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20)
);
CREATE TABLE THREAT (
    Threat_ID INT UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20),
    Description NVARCHAR(1)
);
CREATE TABLE INCIDENT (
    Incident_ID INTEGER UNSIGNED PRIMARY KEY,
    Date_added DATE,
    Priority NVARCHAR(20),
    Status NVARCHAR(20),
    EMPLOYEE_Employee_ID INTEGER UNSIGNED NOT NULL,
    EVENT_Event_ID INTEGER UNSIGNED NOT NULL,
    ITSYSTEM_System_ID INTEGER UNSIGNED NOT NULL,
    VULNERABILITY_Vulnerability_ID INTEGER UNSIGNED NOT NULL,
    THREAT_Threat_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE PROBLEM (
    Problem_ID INTEGER UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20),
    Description NVARCHAR(1),
    Date_added DATE,
    EMPLOYEE_Employee_ID INTEGER UNSIGNED NOT NULL,
    INCIDENT_Incident_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE RISK (
    Risk_ID INTEGER UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20),
    Description NVARCHAR(1),
    Date_added DATE,
    Status NVARCHAR(20),
    PROBLEM_Problem_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE ALERT (
    Alert_ID INTEGER UNSIGNED PRIMARY KEY,
    Date_generated DATE,
    Notification_type CHAR(1),
    EMPLOYEE_Employee_ID INTEGER UNSIGNED NOT NULL,
    INCIDENT_Incident_ID INTEGER UNSIGNED NOT NULL
);
CREATE TABLE VULNERABILITY (
    Vulnerability_ID INTEGER UNSIGNED PRIMARY KEY,
    Name NVARCHAR(20),
    Description NVARCHAR(20),
    Date_identified DATE,
    OPERATION_Operation_ID INTEGER UNSIGNED NOT NULL
);
    
ALTER TABLE BACKUP
    ADD CONSTRAINT BACKUP_OBJECT_FK FOREIGN KEY (OBJECT_Object_ID)
        REFERENCES OBJECT (Object_ID);
        
ALTER TABLE REF_PRIVILEGE 
    ADD CONSTRAINT REF_PRIVILEGE_SUBJECT_FK FOREIGN KEY (SUBJECT_Subject_ID)
        REFERENCES SUBJECT (Subject_ID),
    ADD CONSTRAINT REF_PRIVILEGE_OBJECT_FK FOREIGN KEY (OBJECT_Object_ID)
        REFERENCES OBJECT (Object_ID),
    ADD CONSTRAINT REF_PRIVILEGE_PRIVILEGE_TYPE_FK FOREIGN KEY (PRIVILEGE_TYPE_Privilege_Type_ID)
        REFERENCES PRIVILEGE_TYPE (Privilege_Type_ID);
        
ALTER TABLE SUBJECT
    ADD CONSTRAINT SUBJECT_USER_FK FOREIGN KEY (USER_User_ID)
        REFERENCES User (User_ID);
        
ALTER TABLE OBJECT 
    ADD CONSTRAINT OBJECT_OBJECT_TYPE_FK FOREIGN KEY (OBJECT_TYPE_Object_Type_ID)
        REFERENCES OBJECT_TYPE(Object_Type_ID),
    ADD CONSTRAINT OBJECT_CLASSIFICATION_FK FOREIGN KEY (CLASSIFICATION_Classification_ID)
        REFERENCES CLASSIFICATION (Classification_ID);
        
ALTER TABLE ITSYSTEM
    ADD CONSTRAINT ITSYSTEM_SYSTEM_FK FOREIGN KEY (ITSYSTEM_System_ID)
        REFERENCES ITSYSTEM (System_ID),
    ADD CONSTRAINT ITSYSTEM_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_Employee_ID)
        REFERENCES EMPLOYEE (Employee_ID);
        
ALTER TABLE USER
    ADD CONSTRAINT USER_ITSYSTEM_FK FOREIGN KEY (ITSYSTEM_System_ID)
        REFERENCES ITSYSTEM (System_ID),
    ADD CONSTRAINT USER_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_Employee_ID)
        REFERENCES EMPLOYEE (Employee_ID);
        
ALTER TABLE ROLE
    ADD CONSTRAINT ROLE_ITSYSTEM_FK FOREIGN KEY (ITSYSTEM_System_ID)
        REFERENCES ITSYSTEM (System_ID);
        
ALTER TABLE PRIVILEGE
    ADD CONSTRAINT PRIVILEGE_PRIVILEGE_TYPE_FK FOREIGN KEY(PRIVILEGE_TYPE_Privilege_Type_ID) 
        REFERENCES PRIVILEGE_TYPE(Privilege_Type_ID),
    ADD CONSTRAINT PRIVILEGE_OPERATION_FK FOREIGN KEY(OPERATION_Operation_ID)
        REFERENCES OPERATION(Operation_ID),
    ADD CONSTRAINT PRIVILEGE_ROLE_FK FOREIGN KEY(ROLE_Role_ID) 
        REFERENCES ROLE(Role_ID),
    ADD CONSTRAINT PRIVILEGE_OBJECT_FK FOREIGN KEY (OBJECT_Object_ID) 
        REFERENCES OBJECT(Object_ID);
        
ALTER TABLE OPERATION 
    ADD CONSTRAINT OPERATION_ITSYSTEM_FK FOREIGN KEY (ITSYSTEM_System_ID)
        REFERENCES ITSYSTEM (System_ID),
    ADD CONSTRAINT OPERATION_OPERATION_TYPE_FK FOREIGN KEY (OPERATION_TYPE_Operation_Type_ID)
        REFERENCES OPERATION_TYPE (Operation_Type_ID);
        
ALTER TABLE EVENT 
    ADD CONSTRAINT EVENT_ITSYSTEM_FK FOREIGN KEY (ITSYSTEM_System_ID)
        REFERENCES ITSYSTEM (System_ID),
    ADD CONSTRAINT EVENT_EVENT_TYPE_FK FOREIGN KEY (EVENT_TYPE_Event_Type_ID) 
        REFERENCES EVENT_TYPE (Event_Type_ID),
    ADD CONSTRAINT EVENT_OBJECT_FK FOREIGN KEY (OBJECT_Object_ID) 
        REFERENCES OBJECT (Object_ID),
    ADD CONSTRAINT EVENT_USER_FK FOREIGN KEY (USER_User_ID) 
        REFERENCES USER (User_ID),
    ADD CONSTRAINT EVENT_ROLE_FK FOREIGN KEY (ROLE_Role_ID) 
        REFERENCES ROLE(Role_ID),
    ADD CONSTRAINT EVENT_OBJECT_FK2 FOREIGN KEY (OBJECT_Object_ID2)
        REFERENCES OBJECT (Object_ID),
    ADD CONSTRAINT EVENT_OPERATION_FK FOREIGN KEY (OPERATION_Operation_ID) 
        REFERENCES OPERATION (Operation_ID);
        
ALTER TABLE INCIDENT
    ADD CONSTRAINT INCIDENT_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_Employee_ID) 
        REFERENCES EMPLOYEE(Employee_ID),
    ADD CONSTRAINT INCIDENT_EVENT_FK FOREIGN KEY(EVENT_Event_ID) 
        REFERENCES EVENT(Event_ID),
    ADD CONSTRAINT INCIDENT_ITSYSTEM_FK FOREIGN KEY(ITSYSTEM_System_ID) 
        REFERENCES ITSYSTEM(System_ID),
    ADD CONSTRAINT INCIDENT_VULNERABILITY_FK FOREIGN KEY(VULNERABILITY_Vulnerability_ID) 
        REFERENCES VULNERABILITY(Vulnerability_ID),
    ADD CONSTRAINT INCIDENT_THREAT_FK FOREIGN KEY(THREAT_Threat_ID) 
        REFERENCES THREAT(Threat_ID);
        
ALTER TABLE PROBLEM 
    ADD CONSTRAINT PROBLEM_EMPLOYEE_FK FOREIGN KEY(EMPLOYEE_Employee_ID) 
        REFERENCES EMPLOYEE(Employee_ID),
    ADD CONSTRAINT PROBLEM_INCIDENT_FK FOREIGN KEY(INCIDENT_Incident_ID) 
        REFERENCES INCIDENT(Incident_ID);
        
ALTER TABLE RISK 
    ADD CONSTRAINT RISK_PROBLEM_FK FOREIGN KEY(PROBLEM_Problem_ID) 
    REFERENCES PROBLEM(Problem_ID);
    
ALTER TABLE ALERT
    ADD CONSTRAINT ALERT_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_Employee_ID)
        REFERENCES EMPLOYEE (Employee_ID),
    ADD CONSTRAINT ALERT_INCIDENT_FK FOREIGN KEY (INCIDENT_Incident_ID)
        REFERENCES INCIDENT (Incident_ID);

ALTER TABLE VULNERABILITY 
    ADD CONSTRAINT VULNERABILITY_OPERATION_FK FOREIGN KEY (Operation_Operation_ID)
        REFERENCES OPERATION (OPERATION_ID);
        
ALTER TABLE object 
    ADD Name VARCHAR(100);
        
SET SQL_SAFE_UPDATES = 0;

INSERT INTO EMPLOYEE (Employee_ID, Last_Name, First_Name) VALUES
(1, "Einstein", "Albert"),
(2, "Jarcinska", "Maria"),
(3, "Viana", "Pam"),
(4, "Wyjko","Marcin"),
(5, "Smidt","Jaroslaw"),
(6,"Lalka","Tomasz"),
(7,"Skala","Piotr"),
(8,"Dynka","Anna"),
(9,"Nowotworski","Adam"),
(10,"Krępy","Zdzislaw"),
(11,"Espiel","Karol"),
(12,"Osinska","Anna"),
(13,"Uszka","Karolina"),
(14,"Nyski","Grzegorz"),
(15,"Puzon","Anna"),
(16,"Warzycha","Monika"),
(17,"Czolg","Jacek"),
(18,"Tarnowska","Katarzyna"),
(19,"Mlynska","Hanna"),
(20,"Baszel","Slawomir"),
(21,"Krysicki","Piotr"),
(22,"Maly","Adrian"),
(23,"Ostrow","Gustaw"),
(24,"Bielik","Radoslaw"),
(25,"Klient","Pam");

INSERT INTO Classification(Classification_ID) VALUES (0);
INSERT INTO Object_Type(Object_Type_ID) VALUES (0);

INSERT INTO privilege_type(privilege_type_ID)
VALUES (0);

ALTER TABLE ref_privilege MODIFY PRIVILEGE_ID INT AUTO_INCREMENT;

INSERT INTO ITSystem(System_ID, ITSystem_System_ID, Employee_Employee_ID)
VALUES (0,0,1);

ALTER TABLE ref_privilege
ADD COLUMN Name CHAR;

INSERT INTO object 
VALUES (1, 0, 0, "alert"),
(2, 0, 0, "backup"),
(3, 0, 0, "classification"),
(4, 0, 0, "employee"),
(5, 0, 0, "event"),
(6, 0, 0, "event_type"),
(7, 0, 0, "incident"),
(8, 0, 0, "itsystem"),
(9, 0, 0, "object"),
(10, 0, 0, "object_type"),
(11, 0, 0, "operation"),
(12, 0, 0, "operation_type"),
(13, 0, 0, "privilege"),
(14, 0, 0, "privilege_type"),
(15, 0, 0, "problem"),
(16, 0, 0, "ref_privilege"),
(17, 0, 0, "risk"),
(18, 0, 0, "role"),
(19, 0, 0, "subject"),
(20, 0, 0, "threat"),
(21, 0, 0, "user"),
(22, 0, 0, "vulnerability");

call addUser;
call addSubject;